# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dummy_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Settings_Name', models.CharField(max_length=140, unique=True)),
            ],
        ),
    ]
