# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbStockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ('Symbol', models.CharField(max_length=140, unique=True)),
                ('Sector', models.CharField(blank=True, max_length=100, null=True)),
                ('Exchange', models.CharField(blank=True, max_length=100, null=True)),
                ('Market', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dummy_table',
        ),
    ]
