# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0003_tbmystocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbmystocks',
            name='Symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockData.tbStockList'),
        ),
    ]
