# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0004_auto_20170508_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbmystocks',
            name='Symbol',
        ),
        migrations.DeleteModel(
            name='tbMyStocks',
        ),
    ]
