# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0005_auto_20170508_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbMyStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockData.tbStockList')),
            ],
        ),
    ]
