# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0006_tbmystocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbmystocks',
            name='Symbol',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
